// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: FMSService/internal/FMSProto/records.proto

package FMSProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Records struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordType            string      `protobuf:"bytes,1,opt,name=recordType,proto3" json:"recordType,omitempty"`
	FileName              string      `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	RootDir               string      `protobuf:"bytes,3,opt,name=rootDir,proto3" json:"rootDir,omitempty"`
	Data                  []string    `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	Splitter              string      `protobuf:"bytes,5,opt,name=splitter,proto3" json:"splitter,omitempty"`
	DateTimeFieldLocation int32       `protobuf:"varint,6,opt,name=dateTimeFieldLocation,proto3" json:"dateTimeFieldLocation,omitempty"`
	DateTimeFormat        string      `protobuf:"bytes,7,opt,name=dateTimeFormat,proto3" json:"dateTimeFormat,omitempty"`
	DataSlice             []*KeyValue `protobuf:"bytes,8,rep,name=dataSlice,proto3" json:"dataSlice,omitempty"`
	UnifiedDateFormat     string      `protobuf:"bytes,9,opt,name=unifiedDateFormat,proto3" json:"unifiedDateFormat,omitempty"`
	StoreType             string      `protobuf:"bytes,10,opt,name=storeType,proto3" json:"storeType,omitempty"`
}

func (x *Records) Reset() {
	*x = Records{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FMSService_internal_FMSProto_records_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Records) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Records) ProtoMessage() {}

func (x *Records) ProtoReflect() protoreflect.Message {
	mi := &file_FMSService_internal_FMSProto_records_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Records.ProtoReflect.Descriptor instead.
func (*Records) Descriptor() ([]byte, []int) {
	return file_FMSService_internal_FMSProto_records_proto_rawDescGZIP(), []int{0}
}

func (x *Records) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *Records) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Records) GetRootDir() string {
	if x != nil {
		return x.RootDir
	}
	return ""
}

func (x *Records) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Records) GetSplitter() string {
	if x != nil {
		return x.Splitter
	}
	return ""
}

func (x *Records) GetDateTimeFieldLocation() int32 {
	if x != nil {
		return x.DateTimeFieldLocation
	}
	return 0
}

func (x *Records) GetDateTimeFormat() string {
	if x != nil {
		return x.DateTimeFormat
	}
	return ""
}

func (x *Records) GetDataSlice() []*KeyValue {
	if x != nil {
		return x.DataSlice
	}
	return nil
}

func (x *Records) GetUnifiedDateFormat() string {
	if x != nil {
		return x.UnifiedDateFormat
	}
	return ""
}

func (x *Records) GetStoreType() string {
	if x != nil {
		return x.StoreType
	}
	return ""
}

type KeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values string `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FMSService_internal_FMSProto_records_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_FMSService_internal_FMSProto_records_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_FMSService_internal_FMSProto_records_proto_rawDescGZIP(), []int{1}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValues() string {
	if x != nil {
		return x.Values
	}
	return ""
}

var File_FMSService_internal_FMSProto_records_proto protoreflect.FileDescriptor

var file_FMSService_internal_FMSProto_records_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x46, 0x4d, 0x53, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x46, 0x4d, 0x53, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x66, 0x6d,
	0x73, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xeb, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x74, 0x44, 0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x72, 0x6f, 0x6f, 0x74, 0x44, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x70, 0x6c, 0x69, 0x74, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x70, 0x6c, 0x69, 0x74, 0x74, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x15, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26,
	0x0a, 0x0e, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x30, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x53, 0x6c,
	0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x6d, 0x73, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x64,
	0x61, 0x74, 0x61, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x75, 0x6e, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x75, 0x6e, 0x69, 0x66, 0x69, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65,
	0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x34, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x68, 0x61, 0x6b, 0x72, 0x61, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x2f, 0x46, 0x4d, 0x53, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x46, 0x4d, 0x53, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_FMSService_internal_FMSProto_records_proto_rawDescOnce sync.Once
	file_FMSService_internal_FMSProto_records_proto_rawDescData = file_FMSService_internal_FMSProto_records_proto_rawDesc
)

func file_FMSService_internal_FMSProto_records_proto_rawDescGZIP() []byte {
	file_FMSService_internal_FMSProto_records_proto_rawDescOnce.Do(func() {
		file_FMSService_internal_FMSProto_records_proto_rawDescData = protoimpl.X.CompressGZIP(file_FMSService_internal_FMSProto_records_proto_rawDescData)
	})
	return file_FMSService_internal_FMSProto_records_proto_rawDescData
}

var file_FMSService_internal_FMSProto_records_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_FMSService_internal_FMSProto_records_proto_goTypes = []interface{}{
	(*Records)(nil),  // 0: fmsproto.Records
	(*KeyValue)(nil), // 1: fmsproto.KeyValue
}
var file_FMSService_internal_FMSProto_records_proto_depIdxs = []int32{
	1, // 0: fmsproto.Records.dataSlice:type_name -> fmsproto.KeyValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_FMSService_internal_FMSProto_records_proto_init() }
func file_FMSService_internal_FMSProto_records_proto_init() {
	if File_FMSService_internal_FMSProto_records_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_FMSService_internal_FMSProto_records_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Records); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FMSService_internal_FMSProto_records_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_FMSService_internal_FMSProto_records_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_FMSService_internal_FMSProto_records_proto_goTypes,
		DependencyIndexes: file_FMSService_internal_FMSProto_records_proto_depIdxs,
		MessageInfos:      file_FMSService_internal_FMSProto_records_proto_msgTypes,
	}.Build()
	File_FMSService_internal_FMSProto_records_proto = out.File
	file_FMSService_internal_FMSProto_records_proto_rawDesc = nil
	file_FMSService_internal_FMSProto_records_proto_goTypes = nil
	file_FMSService_internal_FMSProto_records_proto_depIdxs = nil
}
