// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogwriterClient is the client API for Logwriter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogwriterClient interface {
	SaveLog(ctx context.Context, in *LogPayload, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type logwriterClient struct {
	cc grpc.ClientConnInterface
}

func NewLogwriterClient(cc grpc.ClientConnInterface) LogwriterClient {
	return &logwriterClient{cc}
}

func (c *logwriterClient) SaveLog(ctx context.Context, in *LogPayload, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/logwriter.Logwriter/SaveLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogwriterServer is the server API for Logwriter service.
// All implementations must embed UnimplementedLogwriterServer
// for forward compatibility
type LogwriterServer interface {
	SaveLog(context.Context, *LogPayload) (*emptypb.Empty, error)
	mustEmbedUnimplementedLogwriterServer()
}

// UnimplementedLogwriterServer must be embedded to have forward compatible implementations.
type UnimplementedLogwriterServer struct {
}

func (UnimplementedLogwriterServer) SaveLog(context.Context, *LogPayload) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveLog not implemented")
}
func (UnimplementedLogwriterServer) mustEmbedUnimplementedLogwriterServer() {}

// UnsafeLogwriterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogwriterServer will
// result in compilation errors.
type UnsafeLogwriterServer interface {
	mustEmbedUnimplementedLogwriterServer()
}

func RegisterLogwriterServer(s grpc.ServiceRegistrar, srv LogwriterServer) {
	s.RegisterService(&Logwriter_ServiceDesc, srv)
}

func _Logwriter_SaveLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogwriterServer).SaveLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logwriter.Logwriter/SaveLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogwriterServer).SaveLog(ctx, req.(*LogPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// Logwriter_ServiceDesc is the grpc.ServiceDesc for Logwriter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Logwriter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logwriter.Logwriter",
	HandlerType: (*LogwriterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveLog",
			Handler:    _Logwriter_SaveLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loggerService/writer/internal/proto/logWriter.proto",
}
